name: Delivery Feature Request Template
description: File a feature request
title: "[Feature Request] <title>"
labels: ["enhancement"]
assignees: ["pesc4jivs", "thomasfailer"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the feature you requested.
    options:
    - label: I have searched the existing issues
      required: true
- type: dropdown
  attributes:
    label: Product
    options: ['OCC', 'IMP', 'JDT', 'JBOD', 'BOS', 'AI']
    description: The product you what the new feature in
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: A concise description of what you whant.
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the feature you are requesting!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
